#!/bin/sh
set -eu

lb config noauto \
  --mode debian \
  --architectures amd64 \
  --distribution trixie \
  --archive-areas "main contrib non-free-firmware" \
  --binary-images iso-hybrid \
  --debian-installer none \
  --bootloaders "syslinux,grub-efi" \
  --bootappend-live "boot=live components username=omnert hostname=omnertos locales=en_US.UTF-8 keyboard-layouts=us quiet" \
  --iso-application "OmnertOS" \
  --iso-publisher "OmnertOS Project" \
  --iso-volume "OMNERTOS" \
  "${@}"
